# Motivation

## Why This?

  Why have Princeton and Williams topped the US News and World Report ranking charts for so long? What factors are considered when we create college rankings? Though reductionary, college rankings are often what parents and prospective students consider in some way when approaching their college search process. As two students who have worked in admissions, we are excited to dive into this topic.
  
  Name recognition can really go a long way. Rankings do not often change a great deal and there are many aspects that play into how a ranking is constructed based on what the compiler deems important. Because of this, when the US News and World Report changed its ranking methodology multiple times in the 90s, "during that period, a school's ranking could move up or down from one year to the next without any accompanying change in objective quality measures." However, literature has also shown "a correlation between rankings and application decisions, but do not distinguish changes in rank from changes in school quality" (Luca & Smith 59). "Yet, despite serveral methodological flaw, more and more institutions have started to pay attention to their positions in college rankings. Ten years ago, a survey of U.S. college presidents indicated that over 50% of institutions thought rankings were very important for them and had used rankings as an internal benchmark" (Hou et al. 770). 
  
  So, regardless of whether or not a ranking provides comprehensive information, rankings do affect the way that students see schools and the way schools see themselves.

## A snapshot

  In our project, we aim to investigate, visualize, and model those factors that play into college rankings. We then plan to use our findings to create a specialized ranking tool for students. Factors like region, setting, size, admissions rate, diversity, and standardized testing scores play into the score a given school will receive.
  
  

